version: 1
update_configs:
- package_manager: python
  directory: /
  update_schedule: live
  allowed_updates:
  # Create pull requests automatically for any security fixes
  - match:
      update_type: security

  # Create pull requests automatically for any releases to
  # other projects owned by us
  - match:
      dependency_name: cdn-definitions
