AWSTemplateFormatVersion: 2010-09-09

Description: Configuration for exodus-cdn CodePipeline

Parameters:
  env:
    Type: String
    AllowedValues:
      - dev
      - stage
      - prod
    Default: dev
    Description: The environment in which to deploy functions
  oai:
    Type: String
    Description: The origin access identity ID associated with the environment
  repoOwner:
    Type: String
    Default: release-engineering
    Description: The parent of the targeted repository
  repoName:
    Type: String
    Default: exodus-lambda
    Description: The targeted repository
  repoBranch:
    Type: String
    Default: None
    Description: The source branch of the targeted repository
  githubToken:
    Type: String
    Default: None
    Description: A GitHub access token token to authorize webhooks
  region:
    Type: String
    Default: us-east-1
    Description: The region in which resources are established
  email:
    Type: String
    Default: project-exodus@redhat.com
    Description: The email address to which notifications are sent

Conditions:
  IsDev:
    !Equals [!Ref env, dev]
  IsStage:
    !Equals [!Ref env, stage]
  IsProd:
    !Equals [!Ref env, prod]
  NotProd:
    !Not [!Equals [!Ref env, prod]]
  NoBranch:
    !Equals [!Ref repoBranch, None]

Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub exodus-sns-${env}
      Subscription:
        - Endpoint: !Ref email
          Protocol: email

  CodePipelineNotification:
    Type: AWS::CodeStarNotifications::NotificationRule
    Properties:
      Name: !Sub exodus-pipeline-${env}
      DetailType: FULL
      EventTypeIds:
        - codepipeline-pipeline-pipeline-execution-failed
      Resource:
        !Sub arn:aws:codepipeline:${region}:${AWS::AccountId}:${CodePipeline}
      Targets:
        - TargetType: SNS
          TargetAddress: !Sub arn:aws:sns:${region}:${AWS::AccountId}:exodus-sns-${env}

  CodePipelineWebhook:
    Type: AWS::CodePipeline::Webhook
    Condition: NotProd
    Properties:
      Name: !Sub exodus-pipeline-${env}
      AuthenticationConfiguration:
        SecretToken: !Ref githubToken
      Filters:
        - JsonPath: "$.ref"
          MatchEquals:
            !If
              - NoBranch
              - !If
                - IsDev
                - refs/heads/master
                - refs/heads/deploy
              - !Sub refs/heads/${repoBranch}
      Authentication: GITHUB_HMAC
      TargetPipeline: !Ref CodePipeline
      TargetAction: Source
      TargetPipelineVersion: !GetAtt CodePipeline.Version
      RegisterWithThirdParty: true

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub exodus-pipeline-${env}
      ArtifactStore:
        Type: S3
        Location: exodus-pipeline-artifacts
      RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/exodus-codepipe
      Stages:
        # Create Github source for dev, stage pipelines
        - !If
          - NotProd
          - Name: Source
            Actions:
              - Name: Source
                Namespace: SourceVars
                ActionTypeId:
                  Category: Source
                  Owner: ThirdParty
                  Provider: GitHub
                  Version: 1
                Configuration:
                  Owner: !Ref repoOwner
                  Repo: !Ref repoName
                  Branch:
                    !If
                      - NoBranch
                      - !If
                        - IsDev
                        - master
                        - deploy
                      - !Ref repoBranch
                  OAuthToken: !Ref githubToken
                  PollForSourceChanges: false
                OutputArtifacts:
                  - Name: SourceArtifact
          - !Ref AWS::NoValue
        # Create S3 source for prod pipeline
        - !If
          - IsProd
          - Name: Source
            Actions:
              - Name: Source
                ActionTypeId:
                  Category: Source
                  Owner: AWS
                  Provider: S3
                  Version: 1
                Region: !Ref region
                Configuration:
                  S3Bucket: exodus-pipeline-artifacts
                  S3ObjectKey: build-stage
                  PollForSourceChanges: false
                OutputArtifacts:
                  - Name: BuildArtifact
          - !Ref AWS::NoValue
        # Create build stage for dev, stage pipelines
        - !If
          - NotProd
          - Name: Build
            Actions:
              - !If
                - IsStage
                - Name: Verify
                  ActionTypeId:
                    Category: Build
                    Owner: AWS
                    Provider: CodeBuild
                    Version: 1
                  Region: !Ref region
                  Configuration:
                    EnvironmentVariables:
                      !Sub '[
                        {"name": "REPO_OWNER", "value": "${repoOwner}", "type": "PLAINTEXT"},
                        {"name": "REPO_NAME", "value": "${repoName}", "type": "PLAINTEXT"},
                        {"name": "REPO_BRANCH", "value": "${repoBranch}", "type": "PLAINTEXT"},
                        {"name": "COMMIT_ID", "value": "#{SourceVars.CommitId}", "type": "PLAINTEXT"}
                      ]'
                    ProjectName: verify-source
                  InputArtifacts:
                    - Name: SourceArtifact
                  RunOrder: 1
                - !Ref AWS::NoValue
              - Name: Build
                ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Provider: CodeBuild
                  Version: 1
                Region: !Ref region
                Configuration:
                  EnvironmentVariables:
                    !Sub '[{"name": "ENV_TYPE", "value": "${env}", "type": "PLAINTEXT"}]'
                  ProjectName: exodus-codebuild
                InputArtifacts:
                  - Name: SourceArtifact
                OutputArtifacts:
                  - Name: BuildArtifact
                RunOrder: 2
          - !Ref AWS::NoValue
        - Name: Deploy
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_AUTO_EXPAND,CAPABILITY_NAMED_IAM
                ParameterOverrides:
                  !Sub '{"env": "${env}", "oai": "${oai}"}'
                RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/exodus-cloudform
                StackName: !Sub exodus-lambda-${env}
                TemplatePath: BuildArtifact::exodus-lambda-pkg.yaml
              InputArtifacts:
                - Name: BuildArtifact
        # Create promote stage for stage pipeline
        - !If
          - IsStage
          - Name: Promote
            Actions:
              - Name: Approve
                ActionTypeId:
                  Category: Approval
                  Owner: AWS
                  Provider: Manual
                  Version: 1
                Configuration:
                  CustomData: "Approval required for pipeline promotion"
                  NotificationArn: !Sub arn:aws:sns:${region}:${AWS::AccountId}:exodus-sns-${env}
                RunOrder: 1
              - Name: Upload
                ActionTypeId:
                  Category: Deploy
                  Owner: AWS
                  Provider: S3
                  Version: 1
                Region: !Ref region
                Configuration:
                  BucketName: exodus-pipeline-artifacts
                  ObjectKey: !Sub build-${env}
                  Extract: false
                InputArtifacts:
                  - Name: BuildArtifact
                RunOrder: 2
          - !Ref AWS::NoValue

  CodePipelineEventRule:
    Type: AWS::Events::Rule
    # Create event rule for prod pipeline
    Condition: IsProd
    Properties:
      EventPattern:
        source:
          - aws.s3
        detail:
          eventSource:
            - s3.amazonaws.com
          eventName:
            - CopyObject
            - PutObject
            - CompleteMultipartUpload
          requestParameters:
            bucketName:
              - exodus-pipeline-artifacts
            key:
              - build-stage
      Targets:
        - Arn: !Sub arn:aws:codepipeline:${region}:${AWS::AccountId}:${CodePipeline}
          RoleArn: !GetAtt CloudWatchEventRole.Arn
          Id: !Ref CodePipeline

  CodePipelineCloudTrail:
    Type: AWS::CloudTrail::Trail
    # Create trail for prod pipeline
    Condition: IsProd
    Properties:
      S3BucketName: exodus-pipeline-artifacts
      EventSelectors:
        - DataResources:
          - Type: AWS::S3::Object
            Values:
              - arn:aws:s3:::exodus-pipeline-artifacts/build-stage
          ReadWriteType: WriteOnly
      IncludeGlobalServiceEvents: true
      IsLogging: true
      IsMultiRegionTrail: true

  CodePipelineBucket:
    Type: AWS::S3::Bucket
    # Create artifact bucket for dev pipeline
    Condition: IsDev
    Properties:
      BucketName: exodus-pipeline-artifacts
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  CodePipelineBucketPolicy:
    Type: AWS::S3::BucketPolicy
    # Create artifact bucket policy for dev pipeline
    Condition: IsDev
    Properties:
      Bucket: exodus-pipeline-artifacts
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: arn:aws:s3:::exodus-pipeline-artifacts
          - Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub arn:aws:s3:::exodus-pipeline-artifacts/AWSLogs/${AWS::AccountId}/*
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    # Create CodeBuild project for dev pipeline
    Condition: IsDev
    Properties:
      Name: exodus-codebuild
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:2.0
      Source:
        Type: CODEPIPELINE
        BuildSpec: configuration/buildspec.yaml
      Artifacts:
        Type: CODEPIPELINE
      TimeoutInMinutes: 10

  # Create IAM roles for resources, used for all environments
  CodeBuildRole:
    Type: AWS::IAM::Role
    Condition: IsDev
    Properties:
      RoleName: exodus-codebuild
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - codebuild.amazonaws.com
      Policies:
        - PolicyName: exodus-codebuild-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                  - codebuild:*
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
      Path: /

  CloudFormationRole:
    Type: AWS::IAM::Role
    Condition: IsDev
    Properties:
      RoleName: exodus-cloudform
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - cloudformation.amazonaws.com
      Policies:
        - PolicyName: exodus-cloudform-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - iam:*
                  - lambda:*
                  - s3:*
                  - cloudfront:*
                  - cloudwatch:*
                  - cloudformation:*
                Resource:
                  - "*"
      Path: /

  CodePipelineRole:
    Type: AWS::IAM::Role
    Condition: IsDev
    Properties:
      RoleName: exodus-codepipe
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - codepipeline.amazonaws.com
      Policies:
        - PolicyName: exodus-codepipe-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - iam:PassRole
                  - sns:*
                  - lambda:ListFunctions
                  - lambda:InvokeFunction
                  - s3:*
                  - cloudwatch:*
                  - cloudformation:*
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                Resource: "*"
      Path: /

  CloudWatchEventRole:
    Type: AWS::IAM::Role
    Condition: IsProd
    Properties:
      RoleName: !Sub exodus-cloudwatch-${env}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - events.amazonaws.com
      Policies:
        - PolicyName: !Sub exodus-cloudwatch-policy-${env}
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: codepipeline:StartPipelineExecution
                Resource: !Sub arn:aws:codepipeline:${region}:${AWS::AccountId}:${CodePipeline}

Outputs:
  CodePipeline:
    Description: exodus pipeline name
    Value: !Ref CodePipeline
  CodePipelineBucket:
    Description: exodus pipeline artifact bucket ARN
    Value: arn:aws:s3:::exodus-pipeline-artifacts
  CodeBuildProject:
    Description: exodus CodeBuild project ARN
    Value: !Sub arn:aws:codebuild:${region}:${AWS::AccountId}:project/exodus-codebuild
  SNSTopic:
    Description: exodus SNS topic ARN
    Value: !Ref SNSTopic
