AWSTemplateFormatVersion: 2010-09-09

Description: Configuration for verify-source CodeBuild project

Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: verify-source
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:2.0
      Source:
        Type: NO_SOURCE
        BuildSpec: |
          version: 0.2
          phases:
            build:
              commands:
                - aws s3 cp s3://exodus-pipeline-artifacts/.whitelist.gpg .whitelist.gpg
                - gpg --import .whitelist.gpg
                - git clone https://github.com/$REPO_OWNER/$REPO_NAME.git -b $REPO_BRANCH
                - cd ./$REPO_NAME
                - git verify-tag $(git describe --exact-match $COMMIT_ID)
                - aws s3 cp .whitelist.gpg s3://exodus-pipeline-artifacts/.whitelist.gpg
      Artifacts:
        Type: NO_ARTIFACTS
      TimeoutInMinutes: 10

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: verify-source
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - codebuild.amazonaws.com
      Policies:
        - PolicyName: exodus-codebuild-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - codebuild:*
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
      Path: /
